name: Cypress API Tests

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  cypress-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java para Allure
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Instalar dependencias
        run: npm install

      - name: Rodar testes de API com Cypress
        run: npx cypress run --env allure=true,AUTH_USERNAME=${{ secrets.AUTH_USERNAME }},AUTH_PASSWORD=${{ secrets.AUTH_PASSWORD }}

      - name: Gerar relatorio Allure
        run: npm run allure:report

      - name: Upload Allure Report para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/allure-report

  deploy:
    needs: cypress-api
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
