jobs:
  cypress-api:
    runs-on: ubuntu-latest

    env:
      CYPRESS_AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}
      CYPRESS_AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Java para Allure
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Instalar dependencias
        run: npm install

      - name: Rodar testes de API com Cypress
        run: npm run cy:run

      - name: Gerar relatorio Allure
        run: npm run allure:report

      - name: Publicar relatorio Allure como artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report
          retention-days: 7
